### ISSUE TITLE
issue after updating to 55 : Error getting deCONZ data from http://192.168.0.17:8080/api/5F713DB88F.

### ISSUE THREAD

**Issue by pergolafabio** [marthoc/hassio-addons#63]
h, just updated to .55 (from .54)

webinterface wont start anymore, this is in HA log file now : 

2019-01-15 21:55:44 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway. Retrying in 64 seconds
2019-01-15 21:56:49 ERROR (MainThread) [pydeconz.utils] Error getting deCONZ data from http://192.168.0.17:8080/api/5F713DB88F.
2019-01-15 21:56:49 ERROR (MainThread) [pydeconz] Couldn't load data from deCONZ
2019-01-15 21:56:49 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway. Retrying in 128 seconds

log from deconz

[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.55
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyUSB0
/run.sh: 33: [: :false: unexpected operator
[Hass.io] Starting in minimal mode, without VNC GUI
libpng warning: iCCP: known incorrect sRGB profile
21:55:11:505 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
21:55:11:536 CTRL. 3.16.221:55:11:629 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
21:55:11:760 parent process /bin/sh
21:55:11:761 gw run mode: docker/hassio
21:55:11:761 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
21:55:11:763 DB sqlite version 3.16.2
21:55:11:765 DB PRAGMA page_count: 33
21:55:11:765 DB PRAGMA page_size: 4096
21:55:11:766 DB PRAGMA freelist_count: 3
21:55:11:766 DB file size 135168 bytes, free pages 3
21:55:11:766 DB PRAGMA user_version: 6
21:55:11:767 DB cleanup
21:55:11:767 DB create temporary views
21:55:11:769 OSRAM Plug 01: ZHAPower sensor id: 1 ignored loading from database
21:55:11:771 don't close database yet, keep open for 900 seconds
21:55:11:771 started websocket server at port 443
21:55:11:777 discovery updated announce interval to 10 minutes
21:55:11:779 GW firmware update not supported on x86 linux headless
21:55:11:780 found node plugin: libde_rest_plugin.so - REST API Plugin
21:55:11:786 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
21:55:11:794 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
21:55:11:826 discard sensor state push for 2: state/dark (already pushed)
21:55:11:828 discard sensor state push for 2: state/status (already pushed)
21:55:11:829 discard sensor state push for 2: state/lastupdated (already pushed)
This plugin does not support propagateSizeHints()
PROTO: CRC error
21:55:11:887 Device firmware version 0x261F0500
21:55:11:903 unlocked max nodes: 200
21:55:12:512 Device protocol version: 0x0106
21:55:12:529 new node - ext: 0x00212effff02a480, nwk: 0x0000
21:55:12:589 SensorNode 3 set node 0x000d6ffffe1d892c
21:55:12:608 don't close database yet, keep open for 900 seconds
21:55:12:609 LightNode 1: Plug1 added
21:55:12:628 SensorNode 4 set node 0x000d6ffffe25c1d9
21:55:12:641 SensorNode 5 set node 0xd0cf5efffec7f8b4
21:55:12:652 SensorNode 6 set node 0xd0cf5efffebe55ed
21:55:12:664 SensorNode 7 set node 0x90fd9ffffef2f6cc
21:55:12:676 don't close database yet, keep open for 900 seconds
21:55:12:676 LightNode 2: Plug2 added
21:55:12:707 don't close database yet, keep open for 900 seconds
21:55:12:708 LightNode 5: Plug5 added
21:55:12:727 don't close database yet, keep open for 900 seconds
21:55:12:727 LightNode 3: Plug3 added
21:55:12:746 don't close database yet, keep open for 900 seconds
21:55:12:746 LightNode 4: Plug4 added
21:55:12:944 Current channel 11
21:55:13:122 CTRL ANT_CTRL 0x02
21:55:13:553 Device protocol version: 0x0106
21:55:14:578 Current channel 11
21:55:14:722 CTRL ANT_CTRL 0x02
21:55:17:259 Announced to internet
21:55:21:399 ZCL attribute report 0x7CB03EAA00AB4EA0 for cluster 0x0006, ep 0x03
21:55:21:604 Incr. ZDP retry count 2 on item 7
21:55:31:326 ZCL attribute report 0x7CB03EAA0A0284DC for cluster 0x0006, ep 0x03
21:55:34:699 poll node 7c:b0:3e:aa:00:ab:4e:a0-03
21:55:34:723 Incr. ZDP retry count 2 on item 7
21:55:36:699 poll node 7c:b0:3e:aa:0a:02:84:dc-03
21:55:38:699 poll node 7c:b0:3e:aa:0a:01:d7:f4-03
21:55:48:988 0x7CB03EAA0A01D7F4 error APSDE-DATA.confirm: 0xD0 on task
21:55:49:600 scan finished
21:56:11:262 Current channel 11
21:56:12:799 0x7CB03EAA0A01D7F4 error APSDE-DATA.confirm: 0xA7 on task
21:56:40:699 poll node 7c:b0:3e:aa:0a:02:8f:cb-03
21:56:52:910 ZCL attribute report 0x7CB03EAA0A028FCB for cluster 0x0006, ep 0x03
21:57:10:699 poll node 7c:b0:3e:aa:0a:01:ca:1c-03
21:57:11:260 Current channel 11
21:57:15:054 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa00ab4ea0
21:57:15:055 0x7cb03eaa00ab4ea0 found group 0x0001
21:57:15:839 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa0a0284dc
21:57:15:840 0x7cb03eaa0a0284dc found group 0x0001
21:57:16:544 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa0a028fcb
21:57:16:545 0x7cb03eaa0a028fcb found group 0x0001
21:57:21:011 0x7CB03EAA0A01CA1C error APSDE-DATA.confirm: 0xD0 on task
21:57:40:699 poll node 7c:b0:3e:aa:00:ab:4e:a0-03
21:57:40:916 0x7CB03EAA00AB4EA0 error APSDE-DATA.confirm: 0xE9 on task
21:57:42:699 poll node 7c:b0:3e:aa:0a:02:84:dc-03

**Comment by pergolafabio** [comment]
ok, backup and running again, but there is an issue,
seems now phoscon was running on port 80 , instead of 8080
in json :   "web_port": 8080,
but i needed to enter phoscon app, on port 80
deleted integration in hassio, then reauthenticated the conbee again
now up and running, but still on port 80 though

**Comment by marcschumacher** [comment]
I have the same problem (not sure if that helps, but at least @pergolafabio is not the only one)

**Comment by marcschumacher** [comment]
@pergolafabio How did you get back to the old version?

**Comment by pergolafabio** [comment]
see my second reply; fixed it in 55 , didnt roll back
phoscon is on port 80 now,

**Comment by marcschumacher** [comment]
Ah, good hint, thank you!

**Comment by pergolafabio** [comment]
gonna change my router, cause my port 80 was open for ssl renewal , now people externally can now acccess the phoscon app
so be carefull
so gonna disable port forward for now

**Comment by ericvandamme** [comment]
I am guessing the problem lies where ever this line is "/run.sh: 33: [: :false: unexpected operator" resulting in resetting to defaults or something like that. Anyone know where to find this file? Or are the images hashed making them impossible to edit?

**Comment by marcschumacher** [comment]
I guess it is here: 
https://github.com/marthoc/docker-deconz/blob/master/amd64-hassio-addon/run.sh#L33.
My first guess would be that it should be `=` instead of `==` here.

**Comment by ericvandamme** [comment]
Seems so. There is tests being run right now on the docker project; my guess it is a matter of time before a fix is released. You can see the issue here: https://github.com/marthoc/docker-deconz/issues/91

**Comment by SirJMD** [comment]
Issue still persists after "fix".

**Comment by eskimos2000** [comment]
Yeah I got the same phoscan on port 80 now, HA can't see my gateway anymore. upgraded to ver 55-1 still the same port 80.

**Comment by ekufas** [comment]
Same issue for me, also after upgrading to 55.1. Gateway on port 80. Tried to edit config settings to port 80, but HA can't find it. Get the following log:


[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.55
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyAMA0
[Hass.io] Starting in minimal mode, without VNC GUI
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
